---
- name: Workflow var test
  hosts: localhost
  connection: local
  tasks:
    - name: Display initial value of testvar
      ansible.builtin.debug:
        msg: "Initial testvar: {{ testvar }}"

    - name: Set testvar to goodbye
      ansible.builtin.set_fact:
        testvar: "goodbye"

    - name: Display updated value of testvar
      ansible.builtin.debug:
        msg: "Updated testvar: {{ testvar }}"
