---
- name: Fetch /etc/profile and email as attachment
  hosts: all
  become: true  
  become_method: sudo  
  vars_files:
    - vault.yml
  tasks:
    - name: Ensure temporary directory is writable
      ansible.builtin.file:
        path: "/tmp/ansible_tmp"
        state: directory
        mode: '0777'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
      become: false

    - name: Fetch /etc/profile from target host
      ansible.builtin.fetch:
        src: /home/crobb/nfs-sc.yaml
        #src: /etc/profile
        dest: "{{ file_path }}"
        flat: true
        validate_checksum: false
      environment:
        ANSIBLE_TEMPORARY_DIRECTORY: "/tmp/ansible_tmp"
      changed_when: false

    - name: Email /etc/profile as attachment
      community.general.mail:
        host: "{{ smtp_server }}"
        port: "{{ smtp_port }}"
        from: "{{ sender_email }}"
        to: "{{ recipient_email }}"
        subject: "/etc/profile from {{ ansible_hostname }}"
        body: "Please find the /etc/profile file attached."
        attach:
          - "{{ file_path }}"
      delegate_to: localhost  

    - name: Clean up temporary file
      ansible.builtin.file:
        path: "{{ file_path }}"
        state: absent
      become: false
