---
- name: Fetch /etc/profile from AAP
  hosts: k0s.redcomet.ca
  vars_files:
    - ../vault.yml
  tasks:
    - name: Fetch /etc/profile from remote host
      ansible.builtin.fetch:
        src: /etc/profile
        dest: /tmp/fetched_files/
        flat: yes
      register: fetch_result

    - name: print results
      debug:
        msg: "{{ fetch_result }}"

    - name: Send email with /etc/profile as attachment
      community.general.mail:
        host: smtp.gmail.com
        port: 587
        username: "{{ smtp_user }}"
        password: "{{ smtp_pass }}"
        from: "{{ smtp_from }}"
        to: "{{ smtp_to }}"
        subject: Fetched /etc/profile File
        body: Attached is the /etc/profile file from the remote host.
        attach: "{{ fetch_result.dest }}"
        secure: starttls       
      delegate_to: localhost  
