---
- name: Fetch /etc/profile from AAP
  hosts: k0s.redcomet.ca
  become: true
  tasks:
    - name: Fetch /etc/profile from remote host
      ansible.builtin.fetch:
        src: /etc/profile
        dest: /tmp/fetched_files/
        flat: yes
      register: fetch_result

    - name: print results
      debug:
        msg: "{{ fetch_result }}"

    - name: Pause 5 min
      ansible.builtin.pause:
        minutes: 5
