---
- name: Configure Keycloak Realm, User, Clients, and IdP for homelab
  hosts: localhost
  gather_facts: no

  collections:
    - community.general

  vars_files:
    - vault.yml

  tasks:
    - name: Create the homelab realm
      community.general.keycloak_realm:
        auth_client_id: admin-cli
        auth_keycloak_url: "{{ keycloak_url }}"
        auth_realm: master
        auth_username: "{{ keycloak_admin_user }}"
        auth_password: "{{ keycloak_admin_password }}"
        id: "{{ realm_name }}"
        realm: "{{ realm_name }}"
        enabled: true
        state: present

    - name: Create user crobb
      community.general.keycloak_user:
        auth_client_id: admin-cli
        auth_keycloak_url: "{{ keycloak_url }}"
        auth_realm: master
        auth_username: "{{ keycloak_admin_user }}"
        auth_password: "{{ keycloak_admin_password }}"
        realm: "{{ realm_name }}"
        username: "{{ keycloak_username }}"
        enabled: true
        email: "{{ keycloak_email }}"
        email_verified: true
        firstName: "Casey"
        lastName: "Robb"
        credentials:
          - type: password
            value: "{{ keycloak_password }}"
            temporary: false
        state: present

    - name: Assign realm-admin role to crobb
      community.general.keycloak_user_rolemapping:
        auth_client_id: admin-cli
        auth_keycloak_url: "{{ keycloak_url }}"
        auth_realm: master
        auth_username: "{{ keycloak_admin_user }}"
        auth_password: "{{ keycloak_admin_password }}"
        realm: "{{ realm_name }}"
        target_username: "{{ keycloak_username }}"
        client_id: realm-management
        roles:
          - name: realm-admin
        state: present

    - name: Create the groups client scope
      community.general.keycloak_clientscope:
        auth_client_id: admin-cli
        auth_keycloak_url: "{{ keycloak_url }}"
        auth_realm: master
        auth_username: "{{ keycloak_admin_user }}"
        auth_password: "{{ keycloak_admin_password }}"
        realm: "{{ realm_name }}"
        name: groups
        description: "OpenID Connect scope for group membership"
        protocol: openid-connect
        attributes:
          include.in.token.scope: "true"
          include.in.openid.provider.metadata: "true"
          display.on.consent.screen: "true"
        state: present

    - name: Create OIDC client scope with Group Membership mapper
      community.general.keycloak_clientscope:
        auth_client_id: admin-cli
        auth_keycloak_url: "{{ keycloak_url }}"
        auth_realm: master
        auth_username: "{{ keycloak_admin_user }}"
        auth_password: "{{ keycloak_admin_password }}"
        realm: "{{ realm_name }}"
        state: present
        name: groups
        protocol: openid-connect
        protocol_mappers:
          - name: groups
            protocol: openid-connect
            protocolMapper: oidc-group-membership-mapper
            config:
              claim.name: groups
              full.path: "false"
              id.token.claim: "true"
              access.token.claim: "true"
              userinfo.token.claim: "true"

    - name: Create ArgoCD OIDC Client
      community.general.keycloak_client:
        auth_client_id: admin-cli
        auth_keycloak_url: "{{ keycloak_url }}"
        auth_realm: master
        auth_username: "{{ keycloak_admin_user }}"
        auth_password: "{{ keycloak_admin_password }}"
        realm: "{{ realm_name }}"
        client_id: argocd
        name: ArgoCD
        enabled: true
        description: "OIDC Client for ArgoCD"
        client_authenticator_type: client-secret
        secret: "{{ argocd_client_secret }}"
        protocol: openid-connect
        public_client: false
        standard_flow_enabled: true
        direct_access_grants_enabled: true
        root_url: "{{ argocd_url }}"
        redirect_uris:
          - "{{ argocd_url }}/auth/callback"
        web_origins:
          - "+"
        state: present
        default_client_scopes:
          - email
          - groups
          - profile
          - roles
          - web-origins

    - name: Create GitHub Identity Provider
      community.general.keycloak_identity_provider:
        auth_client_id: admin-cli
        auth_keycloak_url: "{{ keycloak_url }}"
        auth_realm: master
        auth_username: "{{ keycloak_admin_user }}"
        auth_password: "{{ keycloak_admin_password }}"
        realm: "{{ realm_name }}"
        alias: github
        provider_id: github
        enabled: true
        config:
          clientId: "{{ github_client_id }}"
          clientSecret: "{{ github_client_secret }}"
          useMetadataFromUrl: "false"
        state: present

    - name: Create group argocd-admins
      community.general.keycloak_group:
        auth_client_id: admin-cli
        auth_keycloak_url: "{{ keycloak_url }}"
        auth_realm: master
        auth_username: "{{ keycloak_admin_user }}"
        auth_password: "{{ keycloak_admin_password }}"
        realm: "{{ realm_name }}"
        name: argocd-admins
        state: present

    - name: Add crobb to argocd-admins
      community.general.keycloak_user:
        auth_client_id: admin-cli
        auth_keycloak_url: "{{ keycloak_url }}"
        auth_realm: master
        auth_username: "{{ keycloak_admin_user }}"
        auth_password: "{{ keycloak_admin_password }}"
        realm: "{{ realm_name }}"
        username: "{{ keycloak_username }}"
        groups:
          - name: argocd-admins
            state: present
        state: present
