---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hibernation-manager
  namespace: open-cluster-management
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hibernation-manager-role
rules:
  - apiGroups: ["hive.openshift.io"]
    resources: ["clusterdeployments"]
    verbs: ["get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hibernation-manager-binding
subjects:
  - kind: ServiceAccount
    name: hibernation-manager
    namespace: open-cluster-management
roleRef:
  kind: ClusterRole
  name: hibernation-manager-role
  apiGroup: rbac.authorization.k8s.io
